name: p4dsdl
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.18
  - pandas=1.0
  - pillow=7.0
  - pip
  - python=3.7
  - scikit-image=0.16
  - scikit-learn=0.22
  - scipy=1.4
  - tensorflow-base=1.15
  - tensorflow=1.15 # or tensorflow-gpu if you have a GPU
  - tensorboard=1.15
  - tensorflow-estimator=1.15
  - tqdm=4.43
  - wheel
  - widgetsnbextension=3.5
  - pip:
    - atari-py==0.2.6
    - gast==0.2.2
    - gym==0.17.1
    - opencv-python==4.2.0.32
    - tensorflow-serving-api==1.15.0 # or tensorflow-serving-api-gpu if GPU
    - urlextract==0.14.0
